### ISSUE TITLE
切割失败

### ISSUE THREAD

**Issue by kevin8990** [song0071000/unpack_plist_png#3]
# 切割失败
## 错误
```
effect_activity/effect_activity_01.png generated
effect_activity/effect_activity_03.png generated
Traceback (most recent call last):
  File "E:\TestPython\unpack.py", line 90, in <module>
    gen_png_from_plist( plist_filename, png_filename )
  File "E:\TestPython\unpack.py", line 73, in gen_png_from_plist
    result_image.paste(rect_on_big, result_box, mask=0)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 1442, in paste
    self.im.paste(im, box)
ValueError: images do not match
```

## effect_activity.png文件
![effect_activity](https://user-images.githubusercontent.com/7582861/46599898-16b02c00-cb1b-11e8-8330-395d0778d67d.png)

## effect_activity.plist文件
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>frames</key>
        <dict>
            <key>effect_activity_01.png</key>
            <dict>
                <key>frame</key>
                <string>{{0,0},{118,124}}</string>
                <key>offset</key>
                <string>{3,-3}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{9,6},{118,124}}</string>
                <key>sourceSize</key>
                <string>{130,130}</string>
            </dict>
            <key>effect_activity_02.png</key>
            <dict>
                <key>frame</key>
                <string>{{46,126},{112,98}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <true/>
                <key>sourceColorRect</key>
                <string>{{0,0},{112,98}}</string>
                <key>sourceSize</key>
                <string>{112,98}</string>
            </dict>
            <key>effect_activity_03.png</key>
            <dict>
                <key>frame</key>
                <string>{{146,29},{103,102}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{103,102}}</string>
                <key>sourceSize</key>
                <string>{103,102}</string>
            </dict>
            <key>effect_activity_04.png</key>
            <dict>
                <key>frame</key>
                <string>{{146,133},{85,98}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <true/>
                <key>sourceColorRect</key>
                <string>{{0,0},{85,98}}</string>
                <key>sourceSize</key>
                <string>{85,98}</string>
            </dict>
            <key>effect_activity_05.png</key>
            <dict>
                <key>frame</key>
                <string>{{0,126},{116,44}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <true/>
                <key>sourceColorRect</key>
                <string>{{0,0},{116,44}}</string>
                <key>sourceSize</key>
                <string>{116,44}</string>
            </dict>
            <key>effect_activity_06.png</key>
            <dict>
                <key>frame</key>
                <string>{{146,0},{107,27}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{107,27}}</string>
                <key>sourceSize</key>
                <string>{107,27}</string>
            </dict>
            <key>effect_activity_07.png</key>
            <dict>
                <key>frame</key>
                <string>{{146,220},{35,37}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <true/>
                <key>sourceColorRect</key>
                <string>{{0,0},{35,37}}</string>
                <key>sourceSize</key>
                <string>{35,37}</string>
            </dict>
        </dict>
        <key>metadata</key>
        <dict>
            <key>format</key>
            <integer>2</integer>
            <key>realTextureFileName</key>
            <string>effect_activity.png</string>
            <key>size</key>
            <string>{256,256}</string>
            <key>smartupdate</key>
            <string>$TexturePacker:SmartUpdate:72805d0d0cfe3883f9e2386a24744e6c$</string>
            <key>textureFileName</key>
            <string>effect_activity.png</string>
        </dict>
    </dict>
</plist>

```

**Comment by kevin8990** [comment]
> ![effect_activity](https://user-images.githubusercontent.com/7582861/46599898-16b02c00-cb1b-11e8-8330-395d0778d67d.png)
> 
> 切割这个，不能成功
> effect_activity.plist文件
> `
> 
> frames effect_activity_01.png frame {{0,0},{118,124}} offset {3,-3} rotated sourceColorRect {{9,6},{118,124}} sourceSize {130,130} effect_activity_02.png frame {{46,126},{112,98}} offset {0,0} rotated sourceColorRect {{0,0},{112,98}} sourceSize {112,98} effect_activity_03.png frame {{146,29},{103,102}} offset {0,0} rotated sourceColorRect {{0,0},{103,102}} sourceSize {103,102} effect_activity_04.png frame {{146,133},{85,98}} offset {0,0} rotated sourceColorRect {{0,0},{85,98}} sourceSize {85,98} effect_activity_05.png frame {{0,126},{116,44}} offset {0,0} rotated sourceColorRect {{0,0},{116,44}} sourceSize {116,44} effect_activity_06.png frame {{146,0},{107,27}} offset {0,0} rotated sourceColorRect {{0,0},{107,27}} sourceSize {107,27} effect_activity_07.png frame {{146,220},{35,37}} offset {0,0} rotated sourceColorRect {{0,0},{35,37}} sourceSize {35,37} metadata format 2 realTextureFileName effect_activity.png size {256,256} smartupdate $TexturePacker:SmartUpdate:72805d0d0cfe3883f9e2386a24744e6c$ textureFileName effect_activity.png `

**Comment by kevin8990** [comment]
应该是Pillow的版本问题
